### ISSUE TITLE
Inverse rendering script

### ISSUE THREAD

**Issue by NIRVANALAN** [marcoamonteiro/pi-GAN#1]
Hi, great work!
I wonder if the inverse rendering(GAN Inversion) script is currently available, and how to use it?

**Comment by marcoamonteiro** [comment]
Hi, 

Thanks for using the repo! We just pushed the inverse rendering script.

**Comment by marcoamonteiro** [comment]
I'm going to close the issue but feel free to re-open if you've got any follow on questions.
