### ISSUE TITLE
TypeError: can't pickle weakref objects

### ISSUE THREAD

**Issue by zwzhang123** [marcoamonteiro/pi-GAN#13]
I fixed it by adding .state_dict():
torch.save(ema.state_dict(), os.path.join(opt.output_dir, now + 'ema.pth'))
torch.save(ema2.state_dict(), os.path.join(opt.output_dir, now + 'ema2.pth'))

**Comment by tomguluson92** [comment]
ME TOO! This problem still exists though changed to DP from the original DDP!

```shell
-> torch.save(ema, os.path.join(opt.output_dir, now + 'ema.pth'))
(Pdb) n
TypeError: cannot pickle 'weakref' object
```

**Comment by xvdp** [comment]
change that line adding .state_dict(), same w all other lines where modules are saved
e.g.  `torch.save(ema.state_dict(), ...`

**Comment by marcoamonteiro** [comment]
This may be related to different library versions since it works on our machines.  Thanks for posting a solution for others who run into this issue.

**Comment by resnant** [comment]
This saved me. Thanks!

**Comment by zzhuolun** [comment]
> change that line adding .state_dict(), same w all other lines where modules are saved e.g. `torch.save(ema.state_dict(), ...`

Thanks!

And in case someone else meets error while updating ema parameters at ` ema.update(generator_ddp.parameters())`, e.g. 

> [ValueError: dictionary update sequence element #0 has length 256; 2 is required]()

don't forget to change the ema loading method to:
```
ema = ExponentialMovingAverage(generator.parameters(), decay=0.999)
ema.load_state_dict(torch.load(os.path.join(opt.load_dir, "ema.pth"), map_location=device))
```

**Comment by ifti1394** [comment]
`1 pickle.dump(model,open('model_70_version_01.pkl','wb'))`

Error is showing : **cannot pickle 'weakref' object**
