### ISSUE TITLE
Errors during training

### ISSUE THREAD

**Issue by athena913** [marcoamonteiro/pi-GAN#2]
Hi,

Thank you for sharing the code for this interesting work. 
I setup a virtualenv and installed the dependencies using "pip install -r requirements.txt". Then I tried to run the training script as follows:  CUDA_VISIBLE_DEVICES=0 python train.py --curriculum CARLA --output_dir  carla_output. But I am getting the following errors, when I tried with python 3.6, 3.7 and 3.8. I am using cuda 10.2.  What version of python should we be using?

1) With python 3.6, installation of requirements fails because there is no matching gdown version 3.12.2 

2) With python 3.7, installation of requirements succeeds, but at runtime there are some errors due to torchvision

3) With python 3.8, installation of requirements succeeds, but I get the following error at runtime: 

   -- Process 0 terminated with the following error:
      Traceback (most recent call last):
        File "/venv_pi_gan/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
                 fn(i, *args)
        File "pi-GAN/train.py", line 181, in train
                torch.save(ema, os.path.join(opt.output_dir, now + 'ema.pth'))
        File "/venv_pi_gan/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
                _save(obj, opened_zipfile, pickle_module, pickle_protocol)
        File "/venv_pi_gan/lib/python3.8/site-packages/torch/serialization.py", line 484, in _save
               pickler.dump(obj)
      TypeError: cannot pickle 'weakref' object

Thanks

**Comment by marcoamonteiro** [comment]
Hi ,

Thanks for pointing out this issue. Glad you're using the repo!

I updated the requirements file and the training script should work now. 

We are using python 3.8 and cuda 11.3. 

I'm going to close the issue but feel free to reopen if training still doesn't work for you.
