### ISSUE TITLE
Error when Rendering Videos

### ISSUE THREAD

**Issue by zhywanna** [marcoamonteiro/pi-GAN#39]
I use the command `python render_video.py ckpt/CelebA/generator.pth --curriculum CelebA --seeds 0 1 2 3` in readme, it seems the pipe is broken?

I tried to re-install `scikit-video,` it doesn't work.

![image](https://user-images.githubusercontent.com/47680024/163787677-97c3bcef-1068-4532-a828-f9058dac1c42.png)

Is there anything I am doing wrong ? Please help me out.

**Comment by onpix** [comment]
Same problem here! Don't know how to solve it.

**Comment by onpix** [comment]
OK, I solved it. For me, it's because the FFmpeg version is too low. run `conda install ffmpeg` would fix it.
You could add `verbosity=1` to `skvideo.io.FFmpegWriter` to see the detailed error message of FFmpeg.

**Comment by zhywanna** [comment]
Hi @creeper121386 ,

I solved the bug same as you. It seems that `scikit-video` use `ffmpeg` as backbone which need to install before. It should have been added in the `requirements.txt` .

**Comment by bernakabadayi** [comment]
it worked for me as well
