### ISSUE TITLE
Multi-GPU training error while training with the `CARLA` curriculum

### ISSUE THREAD

**Issue by inrainbws** [marcoamonteiro/pi-GAN#9]
Hi,

First of all, thanks for sharing this great work. I am currently trying to train a model on images of full-bodies of humans and is using a curriculum based on the CARLA curriculum.  While training on multiple GPUS, I encountered this error:

```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module pa
rameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward p
asses. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameter
s in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model,
it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a var
iable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if
your module graph does not change over iterations.
Parameter at index 52 with name fromRGB.5.model.0.weight has been marked as ready twice. This means that multiple autograd engine  hoo
ks have fired for this particular parameter during this iteration.
```

I noticed that `fromRGB.5.model.0.weight` is a variable in the `ProgressiveEncoderDiscriminator`. Since I have been able to reproduce results with the `Celeba` curriculum, and that the `CARLA` curriculum uses a different Discriminator class, I think the problem can be narrowed down to the  `ProgressiveEncoderDiscriminator` class. But currently I do not have other clues. Could you please have a look at this?

Many thanks and best!

**Comment by ericryanchan** [comment]
Hello,

Thanks for pointing this out! We'll take a closer look. Were you able to train without the error if you tried swapping out the discriminator class? Also what version of Pytorch were you using?

**Comment by Tianhang-Cheng** [comment]
I also met this problem, and I find the cause is the generated image size is different from the setting in the curriculum. So just check your image size, ^_^

**Comment by Totoro97** [comment]
@Tianhang-Cheng Hi I met the same problem. Could you please give more detailed instructions to address this? Thanks very much!

**Comment by Tianhang-Cheng** [comment]
> @Tianhang-Cheng Hi I met the same problem. Could you please give more detailed instructions to address this? Thanks very much!

Sorry, I've forgotten the detail. I just remember that I change the image size of the generator from 64 to 128, but I forgot to change the input size of the discriminator. So when I load from an old checkpoint (which trained under 64×64 resolution), this error occurred. Whatever, I hope this can help you!

**Comment by Tianhang-Cheng** [comment]
Hi @Totoro97, I'm really sorry that I've forgotten the detail. I just remember that I change the image size of the generator from 64 to 128, but I forgot to change the input size of the discriminator. So when I load from an old checkpoint (which trained under 64×64 resolution), this error occurred. Whatever, I hope this can help you!

**Comment by JinWonjoon** [comment]
I think mistake in handling of curriculum bring about this error.

It means, after predetermined steps for certain img size (e.g. step=20e3, img_size=32), dataloader should transform its img_size of real imgs (e.g. from 32 to 64).

But in the original code, dataloader will change its img size when batch size is changed. So, if you set the same batch size in different img_size curriculum, dataloader would not change the img size for real dataset.  

In datasets.py for all Dataset class,
save img_size in Dataset class like,
    `self.img_size = img_size`

In train.py maybe line 163,
    `if not dataloader or dataloader.batch_size != metadata['batch_size']`
to
    `if not dataloader or dataloader.batch_size != metadata['batch_size'] or dataloader.dataset.img_size != metadata['img_size']:`

also, maybe line 190,
    `if dataloader.batch_size != metadata['batch_size']: break`
to
    `if dataloader.batch_size != metadata['batch_size'] or dataloader.dataset.img_size != metadata['img_size']: break`

I think this is not a perfect solution, but I hope it would be helpful.

**Comment by inrainbws** [comment]
> I think mistake in handling of curriculum bring about this error.
> 
> It means, after predetermined steps for certain img size (e.g. step=20e3, img_size=32), dataloader should transform its img_size of real imgs (e.g. from 32 to 64).
> 
> But in the original code, dataloader will change its img size when batch size is changed. So, if you set the same batch size in different img_size curriculum, dataloader would not change the img size for real dataset.
> 
> In datasets.py for all Dataset class, save img_size in Dataset class like, `self.img_size = img_size`
> 
> In train.py maybe line 163, `if not dataloader or dataloader.batch_size != metadata['batch_size']` to `if not dataloader or dataloader.batch_size != metadata['batch_size'] or dataloader.dataset.img_size != metadata['img_size']:`
> 
> also, maybe line 190, `if dataloader.batch_size != metadata['batch_size']: break` to `if dataloader.batch_size != metadata['batch_size'] or dataloader.dataset.img_size != metadata['img_size']: break`
> 
> I think this is not a perfect solution, but I hope it would be helpful.

Thank you! This solved my problem.
